### ISSUE TITLE
Ender dragon server crash

### ISSUE THREAD

**Issue by EvieTheOwl** [TelepathicGrunt/WorldBlender-Fabric#8]
**Version:** 2.1.3 (fabric)
**Environment:** Dedicated server running https://github.com/The-Tiny-Taters/TTTM-AOF which is basically AOF3 2.7.1 but with some additional mods on top

**Description**
You can begin to generate the world for the first time but after about 15 seconds or so the server will crash. Can be fixed by disabling the ender dragon from spawning in the config

**Bug report: (mapped)** https://gist.github.com/profjb58/30a78bb99e64ddc84750fb157e473bbd

**Comment by TelepathicGrunt** [comment]
can you do a test for me? increase the watchdog timer before it stops the game to like 3 minutes or more. The vanilla code to spawn the enderdragon automatically loads a ton of chunks in a single tick so that causes the temporary hang. This log seems like the watchdog timer is too short and is shutting down the server before the vanilla code is able to fully make all the chunks

**Comment by TelepathicGrunt** [comment]
yeah the more I look at this, this is just the watchdog killing the server because the server took a bit extra time to load the extra chunks. I just released an update where I found a way to bypass the chunkloading code in vanilla's enderdragonfight code so now 8 less chunks would be forced to load in one tick. Try the new update and see if the turned off chunkloading code makes the center worldgen generate fast enough that your watchdog settings doesnt shutdown the server. 

(though you really should increase watchdog's timer too as 15 seconds is really short)

**Comment by EvieTheOwl** [comment]
I think 15 seconds was a very bad estimate, apologies for that. Timed it exactly and it took 1 minute 22 seconds to crash but still crashing because of the ender dragon, seems like a different crash log though.

Using the latest version you posted from curseforge

**Crash log (mapped)**: https://gist.github.com/profjb58/f47aaf170b665e226455923321a7e39f

**Comment by EvieTheOwl** [comment]
Joined again to check if it's just the initial generation of the world that's causing the issue but it's still crashing

Some screenies to share what i'm seeing:

**From just flying around a bit outside the loaded chunk area. Seems to load only a few initial chunks properly**
![Image](https://i.imgur.com/4Zt5Fkp.jpg)

**Generated end crystal before I got kicked :P**
![Image](https://i.imgur.com/CAyOBfP.jpg)

**Comment by TelepathicGrunt** [comment]
looks like another part of vanilla code chunkloads a 17x17 area of chunks (289 chunks). I'll try again and see if I can bypass this to be just 2x2 and pray it doesnt break behaviors
![image](https://user-images.githubusercontent.com/40846040/116009457-ce2cc100-a5e7-11eb-8bad-5112c88913b5.png)

**Comment by TelepathicGrunt** [comment]
try v2.1.5 when released. It should bypass that other chunkloading code. I swear to god, the vanilla enderdragonfight class is so  utterly cursed. Hopefully that is the last of the chunkloading code and that world origin wont try and load 289 chunks all at once

**Comment by TelepathicGrunt** [comment]
yeah i think this is as best I can do to stop the chunkload. I'll close this now but hopefully this works for you!
